In [ ]:
import numpy as np
np.__version__

'1.25.2'

Comece gerando dois arrays:
- o primeiro através de amostragem de uma distribuição normal com média 10 e desvio-padrão 2, no formato 5x3.
- o segundo através de amostragem de uma distribuição uniforme com mínimo 25 e máximo 50, no formato 3x4x2.

Para garantir a reprodutibilidade, utilize seed igual a 10.

In [ ]:
rng = ...

In [ ]:
array_1 = ...

In [ ]:
array_1

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

In [ ]:
array_2 = ...

In [ ]:
array_2

array([[[48.33596177, 28.62486737],
        [43.63950528, 28.48378485],
        [47.6632189 , 30.65286084],
        [46.33099375, 32.65794664]],

       [[49.24575921, 37.94585534],
        [33.06186397, 32.06083793],
        [40.1466249 , 33.34411142],
        [41.96621934, 28.86062676]],

       [[31.24438798, 46.74735615],
        [40.00919551, 31.5495764 ],
        [28.73537251, 28.41972874],
        [31.22302344, 34.57061666]]])

#### `np.save`, `np.load`

Salve `array_1` no arquivo `array_1_file`.

In [ ]:
...

Recarregue o array salvo.

In [ ]:
array_1_loaded = ...

In [ ]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

Verifique que os dois arrays são iguais com `np.array_equal`.

In [ ]:
...

True

#### `np.savez`

Salve os dois arrays em um único arquivo `npz`.

In [ ]:
...

Recarregue o arquivo e restaure os dois arrays.

In [ ]:
arrays_loaded = ...

In [ ]:
arrays_loaded

NpzFile 'arrays_savez.npz' with keys: arr_0, arr_1

In [ ]:
array_1_loaded = ...

In [ ]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

In [ ]:
array_2_loaded = ...

In [ ]:
array_2_loaded

array([[[48.33596177, 28.62486737],
        [43.63950528, 28.48378485],
        [47.6632189 , 30.65286084],
        [46.33099375, 32.65794664]],

       [[49.24575921, 37.94585534],
        [33.06186397, 32.06083793],
        [40.1466249 , 33.34411142],
        [41.96621934, 28.86062676]],

       [[31.24438798, 46.74735615],
        [40.00919551, 31.5495764 ],
        [28.73537251, 28.41972874],
        [31.22302344, 34.57061666]]])

#### `np.savez_compressed`

Salve e recarregue os dois arrays em um único arquivo compactado.

In [ ]:
...

In [ ]:
arrays_compacted_loaded = ...

In [ ]:
arrays_compacted_loaded

NpzFile 'arrays_compacted.npz' with keys: arr_0, arr_1

#### `np.savetxt`, `np.loadtxt`

Salve `array_1` em formato `csv`.

In [ ]:
...

Use o comando do Linux abaixo para visualizar como os dados foram salvos no arquivo.

In [ ]:
!head array_csv.csv

7.793323101868935510e+00 8.549950719511119956e+00 8.436389485363886109e+00
1.053395171278878450e+01 9.502838541122217819e+00 1.025296610302370048e+01
1.168608514160867529e+01 1.171587309895153695e+01 1.095036728389717062e+01
9.098462803835166923e+00 8.490135436352497678e+00 8.370371785321818692e+00
9.312290284411478325e+00 9.897239812426132488e+00 8.055452645251286015e+00


Recarregue este array a partir do arquivo.

In [ ]:
array_1_loaded = ...

In [ ]:
array_1_loaded

array([[ 7.7933231 ,  8.54995072,  8.43638949],
       [10.53395171,  9.50283854, 10.2529661 ],
       [11.68608514, 11.7158731 , 10.95036728],
       [ 9.0984628 ,  8.49013544,  8.37037179],
       [ 9.31229028,  9.89723981,  8.05545265]])

Use `np.array_equal` para verificar que, mesmo quando salvo como `csv`, o array recarregado é igual ao array original.

In [ ]:
...

True