In [2]:
import numpy as np

# ndarray e atributos

## Array a partir de dados

In [3]:
array_from_list = np.array([1,2,3])
array_from_list

array([1, 2, 3])

In [4]:
list_a = [1,2,3]
type(list_a)

list

In [5]:
array_from_list = np.array(list_a)
array_from_list

array([1, 2, 3])

In [7]:
type(array_from_list)

numpy.ndarray

In [8]:
tuple_a = (1,2,3)
tuple_a

(1, 2, 3)

In [9]:
type(tuple_a)

tuple

In [11]:
array_from_tuple = np.array(tuple_a)
array_from_tuple

array([1, 2, 3])

In [12]:
array_from_list + 5

array([6, 7, 8])

In [13]:
set_a = {1,2,3,4}
print(set_a)
print(type(set_a))

{1, 2, 3, 4}
<class 'set'>


In [14]:
array_from_set = np.array(set_a)
array_from_set

array({1, 2, 3, 4}, dtype=object)

In [15]:
array_from_set + 5

TypeError: unsupported operand type(s) for +: 'set' and 'int'

In [17]:
dict_a = {1: 'a', 2: 'b'}
print(dict_a)
print(type(dict_a))

{1: 'a', 2: 'b'}
<class 'dict'>


In [18]:
array_from_dict = np.array(dict_a)
array_from_dict

array({1: 'a', 2: 'b'}, dtype=object)

In [19]:
array_from_dict + 5

TypeError: unsupported operand type(s) for +: 'dict' and 'int'

## Array de 1 dimensão

## Array de 2 dimensão

In [21]:
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9],
                     [10,11,12]])
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
array_2d[1][1], array_2d[3][2]

(np.int64(5), np.int64(12))

## Array de n dimensões

In [29]:
array_3d = np.array([[[1,2,3],
                     [4,5,6],
                     [7,8,9],
                     [10,11,12]],
                    
                    [[13,14,15],
                    [16,17,18],
                    [19,20,21],
                    [22,23,24]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [31]:
array_3d[0][2][1]

np.int64(8)

In [33]:
array_3d[1][0]

array([13, 14, 15])

## Atributos do array

### Size

In [34]:
array_from_list

array([1, 2, 3])

In [35]:
array_from_list.size

3

In [36]:
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
array_2d.size

12

In [38]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [39]:
array_3d.size

24

### ndim

In [40]:
array_from_list.ndim

1

In [41]:
array_2d.ndim

2

In [42]:
array_3d.ndim

3

### shape

In [43]:
array_from_list.shape

(3,)

In [44]:
array_2d.shape

(4, 3)

In [45]:
array_3d.shape

(2, 4, 3)

In [46]:
len(array_3d)

2

### itemsize

In [47]:
array_from_list.itemsize

8

In [48]:
array_2d.itemsize

8

In [49]:
array_3d.itemsize

8

### nbytes

In [50]:
array_from_list.nbytes

24

In [51]:
array_2d.nbytes

96

In [52]:
array_3d.nbytes

192

### dtype

In [53]:
array_from_list.dtype

dtype('int64')

In [54]:
array_2d.dtype

dtype('int64')

In [55]:
array_3d.dtype

dtype('int64')

In [56]:
np.array([1,2,3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [57]:
np.array([1,2,3], dtype=np.str_)

array(['1', '2', '3'], dtype='<U1')

In [58]:
np.array([1,2,3], dtype=float).dtype

dtype('float64')