# Funções Universais

In [1]:
import numpy as np

## Ufuncs

In [2]:
rng = np.random.default_rng(seed=2)

In [4]:
array_1 = rng.integers(low=-10, high=10, size=20).reshape(4,5)
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [5]:
array_2 = rng.integers(low=-10, high=10, size=20).reshape(4,5)
array_2

array([[ -4,   1,  -5,  -7,   4],
       [ -2,   3,   3,   8,  -2],
       [ -6,   2,   8,   9,   7],
       [  3,  -3,  -3, -10,  -7]])

## Funções Matemáticas

``np.add, np.subtract, np.multiply e np.divide``

In [6]:
np.add(array_1, array_2)

array([[  2,  -4, -13, -12,   2],
       [  4,   2,  -6,   4,   0],
       [  0,   6,  17,   2,  14],
       [ -6,  -2,  -8, -16,  -4]])

In [7]:
np.subtract(array_1, array_2)

array([[ 10,  -6,  -3,   2,  -6],
       [  8,  -4, -12, -12,   4],
       [ 12,   2,   1, -16,   0],
       [-12,   4,  -2,   4,  10]])

In [8]:
np.multiply(array_1, array_2)

array([[-24,  -5,  40,  35,  -8],
       [-12,  -3, -27, -32,  -4],
       [-36,   8,  72, -63,  49],
       [-27,  -3,  15,  60, -21]])

In [9]:
np.divide(array_1, array_2)

array([[-1.5       , -5.        ,  1.6       ,  0.71428571, -0.5       ],
       [-3.        , -0.33333333, -3.        , -0.5       , -1.        ],
       [-1.        ,  2.        ,  1.125     , -0.77777778,  1.        ],
       [-3.        , -0.33333333,  1.66666667,  0.6       , -0.42857143]])

``np.mod``

In [10]:
np.mod(array_1, 2)

array([[0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1]])

``np.divmod``

In [11]:
np.divmod(array_1, 2)

(array([[ 3, -3, -4, -3, -1],
        [ 3, -1, -5, -2,  1],
        [ 3,  2,  4, -4,  3],
        [-5,  0, -3, -3,  1]]),
 array([[0, 1, 0, 1, 0],
        [0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1],
        [1, 1, 1, 0, 1]]))

``np.absolute``

In [12]:
array_1

array([[ 6, -5, -8, -5, -2],
       [ 6, -1, -9, -4,  2],
       [ 6,  4,  9, -7,  7],
       [-9,  1, -5, -6,  3]])

In [13]:
np.absolute(array_1)

array([[6, 5, 8, 5, 2],
       [6, 1, 9, 4, 2],
       [6, 4, 9, 7, 7],
       [9, 1, 5, 6, 3]])

``np.diff``

In [15]:
np.diff(a = array_1)

array([[-11,  -3,   3,   3],
       [ -7,  -8,   5,   6],
       [ -2,   5, -16,  14],
       [ 10,  -6,  -1,   9]])

In [16]:
np.diff(array_1, axis=0)

array([[  0,   4,  -1,   1,   4],
       [  0,   5,  18,  -3,   5],
       [-15,  -3, -14,   1,  -4]])

In [18]:
np.diff(array_1, n = 2)

array([[  8,   6,   0],
       [ -1,  13,   1],
       [  7, -21,  30],
       [-16,   5,  10]])

``np.power, np.exp e np.log``

In [19]:
np.power(array_1, 2) # elevar o número ao quadrado

array([[36, 25, 64, 25,  4],
       [36,  1, 81, 16,  4],
       [36, 16, 81, 49, 49],
       [81,  1, 25, 36,  9]])

In [21]:
np.power(array_1, [[2], [2], [3], [3]])

array([[  36,   25,   64,   25,    4],
       [  36,    1,   81,   16,    4],
       [ 216,   64,  729, -343,  343],
       [-729,    1, -125, -216,   27]])

In [22]:
np.power(array_1, [[2, 2, 3, 3, 3]])

array([[  36,   25, -512, -125,   -8],
       [  36,    1, -729,  -64,    8],
       [  36,   16,  729, -343,  343],
       [  81,    1, -125, -216,   27]])

In [23]:
np.exp(array_1) # calculo e**valor

array([[4.03428793e+02, 6.73794700e-03, 3.35462628e-04, 6.73794700e-03,
        1.35335283e-01],
       [4.03428793e+02, 3.67879441e-01, 1.23409804e-04, 1.83156389e-02,
        7.38905610e+00],
       [4.03428793e+02, 5.45981500e+01, 8.10308393e+03, 9.11881966e-04,
        1.09663316e+03],
       [1.23409804e-04, 2.71828183e+00, 6.73794700e-03, 2.47875218e-03,
        2.00855369e+01]])

In [24]:
np.log(array_1)

/tmp/ipykernel_9337/3647096076.py:1: RuntimeWarning: invalid value encountered in log
  np.log(array_1)


array([[1.79175947,        nan,        nan,        nan,        nan],
       [1.79175947,        nan,        nan,        nan, 0.69314718],
       [1.79175947, 1.38629436, 2.19722458,        nan, 1.94591015],
       [       nan, 0.        ,        nan,        nan, 1.09861229]])

``np.reciprocal``

In [26]:
np.reciprocal(array_1.astype(float)) # 1 / valor

array([[ 0.16666667, -0.2       , -0.125     , -0.2       , -0.5       ],
       [ 0.16666667, -1.        , -0.11111111, -0.25      ,  0.5       ],
       [ 0.16666667,  0.25      ,  0.11111111, -0.14285714,  0.14285714],
       [-0.11111111,  1.        , -0.2       , -0.16666667,  0.33333333]])

``np.sqrt e np.cbrt``

In [27]:
np.sqrt(array_1)

/tmp/ipykernel_9337/3607161969.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array_1)


array([[2.44948974,        nan,        nan,        nan,        nan],
       [2.44948974,        nan,        nan,        nan, 1.41421356],
       [2.44948974, 2.        , 3.        ,        nan, 2.64575131],
       [       nan, 1.        ,        nan,        nan, 1.73205081]])

In [28]:
np.cbrt(array_1)

array([[ 1.81712059, -1.70997595, -2.        , -1.70997595, -1.25992105],
       [ 1.81712059, -1.        , -2.08008382, -1.58740105,  1.25992105],
       [ 1.81712059,  1.58740105,  2.08008382, -1.91293118,  1.91293118],
       [-2.08008382,  1.        , -1.70997595, -1.81712059,  1.44224957]])

``np.gcd e np.lcm``

In [29]:
array_1, array_2

(array([[ 6, -5, -8, -5, -2],
        [ 6, -1, -9, -4,  2],
        [ 6,  4,  9, -7,  7],
        [-9,  1, -5, -6,  3]]),
 array([[ -4,   1,  -5,  -7,   4],
        [ -2,   3,   3,   8,  -2],
        [ -6,   2,   8,   9,   7],
        [  3,  -3,  -3, -10,  -7]]))

In [30]:
np.gcd(array_1, array_2)

array([[2, 1, 1, 1, 2],
       [2, 1, 3, 4, 2],
       [6, 2, 1, 1, 7],
       [3, 1, 1, 2, 1]])

In [31]:
np.lcm(array_1, array_2)

array([[12,  5, 40, 35,  4],
       [ 6,  3,  9,  8,  2],
       [ 6,  4, 72, 63,  7],
       [ 9,  3, 15, 30, 21]])

## Funções de comparação

``np.maximum e np.minimum``

In [32]:
array_1, array_2

(array([[ 6, -5, -8, -5, -2],
        [ 6, -1, -9, -4,  2],
        [ 6,  4,  9, -7,  7],
        [-9,  1, -5, -6,  3]]),
 array([[ -4,   1,  -5,  -7,   4],
        [ -2,   3,   3,   8,  -2],
        [ -6,   2,   8,   9,   7],
        [  3,  -3,  -3, -10,  -7]]))

In [33]:
np.maximum(array_1, array_2)

array([[ 6,  1, -5, -5,  4],
       [ 6,  3,  3,  8,  2],
       [ 6,  4,  9,  9,  7],
       [ 3,  1, -3, -6,  3]])

In [34]:
np.minimum(array_1, array_2)

array([[ -4,  -5,  -8,  -7,  -2],
       [ -2,  -1,  -9,  -4,  -2],
       [ -6,   2,   8,  -7,   7],
       [ -9,  -3,  -5, -10,  -7]])

``np.greater, np.greater_equal, np.less, np.less_equal, np.not_equal e np.equal``

In [35]:
np.greater(array_1, array_2)

array([[ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False],
       [False,  True, False,  True,  True]])

In [36]:
np.less_equal(array_1, array_2)

array([[False,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True,  True],
       [ True, False,  True, False, False]])

In [37]:
np.equal(array_1, array_2)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

``logical_and, logical_or, logical_xor e logical_not``

In [38]:
comparison_1 = array_1 > 0
comparison_1

array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False, False,  True]])

In [40]:
comparison_2 = np.mod(array_1, 2) == 0
comparison_2

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False,  True, False]])

In [41]:
np.logical_and(comparison_1, comparison_2) # todos os valores positivos E pares

array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [43]:
np.logical_or(comparison_1, comparison_2) # todos os valores positivos OU pares

array([[ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True]])

In [44]:
np.logical_not(comparison_1, comparison_2) # todos os valores positivos NÃO pares

array([[False,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False, False, False,  True, False],
       [ True, False,  True,  True, False]])

In [45]:
np.logical_xor(comparison_1, comparison_2) # todos os valores positivos 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

``np.isclose e np.allclose``

In [46]:
array_1 = np.array([-1.1558, 0.8994, 3.2894])
array_2 = np.array([-1.1557, 0.8993, 3.2895])

In [47]:
np.isclose(a=array_1, b=array_2, atol=0.0001)

array([ True,  True,  True])

In [48]:
np.allclose(a=array_1, b=array_2, atol=0.0001)

True

``np.array_equal``

In [49]:
array_1 = np.arange(20).reshape(4,5)
array_2 = np.arange(20).reshape(4,5)

In [50]:
array_1, array_2

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]))

In [51]:
np.array_equal(array_1, array_2)

True

## Funções float

``np.isfinite, np.isinf, np.isneginf, np.isnan``

In [52]:
np.divide(1,0)

/tmp/ipykernel_9337/1233628259.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(1,0)


np.float64(inf)

In [53]:
np.isfinite(np.divide(1,0))

/tmp/ipykernel_9337/185974667.py:1: RuntimeWarning: divide by zero encountered in divide
  np.isfinite(np.divide(1,0))


np.False_

In [54]:
np.isinf(np.divide(1,0))

/tmp/ipykernel_9337/4110478506.py:1: RuntimeWarning: divide by zero encountered in divide
  np.isinf(np.divide(1,0))


np.True_

In [56]:
np.isneginf(np.divide(-1,0))

/tmp/ipykernel_9337/1999854301.py:1: RuntimeWarning: divide by zero encountered in divide
  np.isneginf(np.divide(-1,0))


np.True_

In [57]:
np.isnan(np.log(-1))

/tmp/ipykernel_9337/916304143.py:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(-1))


np.True_

``np.floor, np.ceil, np.trunc``

In [58]:
np.floor([-3.6, 2.7, 0.4, 7.0])

array([-4.,  2.,  0.,  7.])

In [59]:
np.ceil([-3.6, 2.7, 0.4, 7.0])

array([-3.,  3.,  1.,  7.])

In [60]:
np.trunc([-3.6, 2.7, 0.4, 7.0])

array([-3.,  2.,  0.,  7.])