# Métodos de Conversão

In [2]:
import numpy as np

In [4]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [5]:
array_3d = np.arange(1, 25).reshape(2, 4, 3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## tolist

In [6]:
array_3d.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
 [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]

In [7]:
type(array_3d.tolist())

list

## item

In [8]:
array_3d[1, 0, 2]

np.int64(15)

In [9]:
array_3d.item((1, 0, 2))

15

In [10]:
array_3d.item((14))

15

## view

In [16]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [17]:
array_view = array_3d.view()
array_view

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [18]:
array_view[0,0,0] = 0
array_view

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [19]:
array_3d

array([[[ 0,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## copy

In [20]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_copy = array_3d.copy()
array_copy

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [21]:
array_copy[0,0,0] = 99
array_copy

array([[[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [22]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## fill

In [23]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_3d.fill(55)
array_3d

array([[[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]],

       [[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]]])

# Métodos de manipulação de `shape`

In [24]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [25]:
array_3d.shape

(2, 4, 3)

In [26]:
array_3d.reshape(4, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [28]:
array_3d.reshape(5, 2, 1)

ValueError: cannot reshape array of size 24 into shape (5,2,1)

In [29]:
array_3d.reshape(4, 3, -1)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [30]:
array_3d.reshape(4, -1, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

## transpose

In [31]:
array_transpose = array_3d.transpose((1,0,2))
array_transpose

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

## swapaxes

In [32]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [33]:
array_3d.swapaxes(1, 0)

array([[[ 1,  2,  3],
        [13, 14, 15]],

       [[ 4,  5,  6],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [19, 20, 21]],

       [[10, 11, 12],
        [22, 23, 24]]])

## flatten

In [34]:
array_3d.flatten() # copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## ravel

In [35]:
array_3d.ravel() # view

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## squeeze

In [37]:
array_axis_size_1 = array_3d.reshape(8, 1, 3)
array_axis_size_1

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]],

       [[16, 17, 18]],

       [[19, 20, 21]],

       [[22, 23, 24]]])

In [38]:
array_axis_size_1.shape

(8, 1, 3)

In [39]:
array_squeeze = array_axis_size_1.squeeze()

# Método de seleção e manipulação de itens

## `take`

In [41]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [42]:
array_3d.take(indices = [1, 5, 10, 12])

array([ 2,  6, 11, 13])

In [43]:
array_3d.take(indices = [[1, 5], [10, 12]])

array([[ 2,  6],
       [11, 13]])

## `put`

In [45]:
array_3d.put(indices = [1, 5, 10, 12], values = [50,56,61,63])
array_3d

array([[[ 1, 50,  3],
        [ 4,  5, 56],
        [ 7,  8,  9],
        [10, 61, 12]],

       [[63, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## `repeat`

In [46]:
array_3d = np.arange(1, 25).reshape(2,4,3)
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [48]:
array_3d.repeat(repeats = 3)

array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11, 12,
       12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17,
       18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23,
       23, 24, 24, 24])

## `sort`

## `argsort`

## `take`

## `take`

## `take`

## `take`

## `take`

## `take`

## `take`

## `take`