In [3]:
import numpy as np

# Agrupamento e dividindo arrays

In [4]:
array_1d = np.arange(0, 10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array_2d_0 = np.arange(0, 18).reshape(3, 6)
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [6]:
array_2d_1 = np.arange(18, 36).reshape(3, 6)
array_2d_1

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## `np.concatenate`

In [7]:
np.concatenate([array_2d_0, array_2d_1])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [8]:
np.concatenate([array_2d_0, array_2d_1], axis = 1)

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

## `np.stack`

In [9]:
array_stacked = np.stack(arrays= [array_2d_0, array_2d_1])
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [10]:
array_stacked.shape

(2, 3, 6)

In [11]:
array_stacked = np.stack(arrays= [array_2d_0, array_2d_1], axis = 1)
array_stacked

array([[[ 0,  1,  2,  3,  4,  5],
        [18, 19, 20, 21, 22, 23]],

       [[ 6,  7,  8,  9, 10, 11],
        [24, 25, 26, 27, 28, 29]],

       [[12, 13, 14, 15, 16, 17],
        [30, 31, 32, 33, 34, 35]]])

In [12]:
array_stacked.shape

(3, 2, 6)

In [13]:
array_stacked = np.stack(arrays= [array_2d_0, array_2d_1], axis = -1)
array_stacked

array([[[ 0, 18],
        [ 1, 19],
        [ 2, 20],
        [ 3, 21],
        [ 4, 22],
        [ 5, 23]],

       [[ 6, 24],
        [ 7, 25],
        [ 8, 26],
        [ 9, 27],
        [10, 28],
        [11, 29]],

       [[12, 30],
        [13, 31],
        [14, 32],
        [15, 33],
        [16, 34],
        [17, 35]]])

In [14]:
array_stacked.shape

(3, 6, 2)

## `np.vstack e np.hstack`

In [15]:
np.vstack(tup = [array_2d_0, array_2d_1]) # np.concatenate axis = 0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [16]:
np.hstack(tup = [array_2d_0, array_2d_1]) # np.concatenate axis = 1

array([[ 0,  1,  2,  3,  4,  5, 18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11, 24, 25, 26, 27, 28, 29],
       [12, 13, 14, 15, 16, 17, 30, 31, 32, 33, 34, 35]])

## `np.split`

In [17]:
np.split(ary=array_1d, indices_or_sections=2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [18]:
np.split(ary=array_2d_0, indices_or_sections=3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [19]:
np.split(ary=array_2d_0, indices_or_sections=3, axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [20]:
np.split(ary=array_2d_0, indices_or_sections= [2, 3], axis=1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

## `np.vsplit e np.hsplit`

In [21]:
np.vsplit(ary= array_2d_0, indices_or_sections= 3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [22]:
np.hsplit(ary= array_2d_0, indices_or_sections= 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [23]:
np.hsplit(ary= array_2d_0, indices_or_sections= [2,3])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2],
        [ 8],
        [14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

# Adicionando eixos

## `np.expand_dims`

In [24]:
array_2d_0.ndim

2

In [25]:
array_2d_0.shape

(3, 6)

In [27]:
new_array_2d_0 = np.expand_dims(a = array_2d_0, axis = 0)
new_array_2d_0

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]])

In [28]:
new_array_2d_0.ndim, new_array_2d_0.shape

(3, (1, 3, 6))

In [29]:
np.squeeze(new_array_2d_0).shape

(3, 6)

In [30]:
new_array_2d_0 = np.expand_dims(a = array_2d_0, axis = 1)
new_array_2d_0

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]]])

In [31]:
new_array_2d_0.ndim, new_array_2d_0.shape

(3, (3, 1, 6))

In [34]:
array_2d_0[np.newaxis, :], array_2d_0[np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]]]),
 (1, 3, 6))

In [35]:
array_2d_0[:, np.newaxis, :], array_2d_0[:, np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4,  5]],
 
        [[ 6,  7,  8,  9, 10, 11]],
 
        [[12, 13, 14, 15, 16, 17]]]),
 (3, 1, 6))

In [36]:
array_2d_0.reshape(3, 1, 6)

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17]]])

# Rearranjando elementos

## `np.flip`

In [39]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.flip(array_1d)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
array_1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
np.flip(array_2d_0)

array([[17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [42]:
np.flip(array_2d_0, axis = 0)

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [43]:
np.flip(array_2d_0, axis = 1)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12]])

## `np.resize`

In [44]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [45]:
np.resize(a = array_2d_0, new_shape=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.resize(a = array_2d_0, new_shape= (4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [47]:
np.resize(a = array_2d_0, new_shape= (8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

# Adicionando ou removendo elementos

## `np.insert`

In [48]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.insert(arr = array_1d, obj=4, values= -1)

array([ 0,  1,  2,  3, -1,  4,  5,  6,  7,  8,  9])

In [51]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [52]:
np.insert(arr=array_2d_0, obj=1, values=-1, axis=1)

array([[ 0, -1,  1,  2,  3,  4,  5],
       [ 6, -1,  7,  8,  9, 10, 11],
       [12, -1, 13, 14, 15, 16, 17]])

In [53]:
np.insert(arr=array_2d_0, obj=1, values= [-1, -2, -3], axis=1)

array([[ 0, -1,  1,  2,  3,  4,  5],
       [ 6, -2,  7,  8,  9, 10, 11],
       [12, -3, 13, 14, 15, 16, 17]])

## `np.delete`

In [54]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.delete(arr=array_1d, obj = 4)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [56]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [57]:
np.delete(arr = array_2d_0, obj = 1, axis=1)

array([[ 0,  2,  3,  4,  5],
       [ 6,  8,  9, 10, 11],
       [12, 14, 15, 16, 17]])

## `np.append`

In [58]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.append(arr=array_1d, values=[0,1,2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [61]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [64]:
np.append(arr=array_2d_0, values=[[0, 1, 2, 3, 4, 5]], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5]])

In [65]:
np.append(arr=array_2d_0, values=[[0], [6], [12]], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0],
       [ 6,  7,  8,  9, 10, 11,  6],
       [12, 13, 14, 15, 16, 17, 12]])

## `np.tile`

In [66]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.tile(A= array_1d, reps=2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.tile(A = array_1d, reps=(2, 2))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
array_2d_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [71]:
np.tile(A = array_2d_0, reps=(3, 2))

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 12, 13, 14, 15, 16, 17]])

## `np.pad`

In [72]:
array_pad_1d = np.array([1,2,3])


In [74]:
np.pad(array = array_pad_1d, pad_width=(1, 2), mode='constant', constant_values = (10, 20))

array([10,  1,  2,  3, 20, 20])

In [75]:
np.pad(array = array_pad_1d, pad_width=(1, 2), mode='edge')

array([1, 1, 2, 3, 3, 3])

In [76]:
np.pad(array = array_pad_1d, pad_width=(1, 2), mode='minimum')

array([1, 1, 2, 3, 1, 1])

In [78]:
np.pad(array = array_pad_1d, pad_width=(1, 2), mode='maximum')

array([3, 1, 2, 3, 3, 3])

In [79]:
np.pad(array = array_pad_1d, pad_width=(1, 2), mode='mean')

array([2, 1, 2, 3, 2, 2])

## `np.trim_zeros`

In [81]:
array_with_zeros = np.array([0,0,1,2,3,4,0,0,0])
array_with_zeros

array([0, 0, 1, 2, 3, 4, 0, 0, 0])

In [82]:
np.trim_zeros(filt=array_with_zeros)

array([1, 2, 3, 4])

In [83]:
np.trim_zeros(filt=array_with_zeros, trim='f')

array([1, 2, 3, 4, 0, 0, 0])

In [84]:
np.trim_zeros(filt=array_with_zeros, trim='b')

array([0, 0, 1, 2, 3, 4])

# Obtendo valores únicos

## `np.unique`

In [85]:
array_unique = np.array([7,8,8,6,8,7,7])

In [86]:
np.unique(ar=array_unique)

array([6, 7, 8])

In [87]:
np.unique(ar=array_unique, return_index=True)

(array([6, 7, 8]), array([3, 0, 1]))

In [89]:
unique_values, indices = np.unique(ar=array_unique, return_inverse=True)
unique_values, indices

(array([6, 7, 8]), array([1, 2, 2, 0, 2, 1, 1]))

In [92]:
unique_values[indices]

array([7, 8, 8, 6, 8, 7, 7])

In [93]:
np.unique(ar=array_unique, return_counts=True)

(array([6, 7, 8]), array([1, 3, 3]))

In [94]:
array_unique_2d = np.array([[0,1,2],
                            [3,4,5],
                            [0,1,2]])

In [95]:
np.unique(ar = array_unique_2d, return_counts=True)

(array([0, 1, 2, 3, 4, 5]), array([2, 2, 2, 1, 1, 1]))

In [96]:
np.unique(ar = array_unique_2d, return_counts=True, axis=0)

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([2, 1]))