In [2]:
import numpy as np

# Funções de indexação

## `np.nonzero`

In [3]:
array = np.array([[1,0,0],
                  [0,2,0],
                  [3,4,0]])

In [4]:
indices = np.nonzero(array)
indices

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [5]:
array[indices]

array([1, 2, 3, 4])

## `np.where`

In [6]:
array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.where(array_1d < 4)

(array([0, 1, 2, 3]),)

In [8]:
np.where(array_1d < 4, 0, 1)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [10]:
np.where(array_1d < 4, array_1d, array_1d + 10)

array([ 0,  1,  2,  3, 14, 15, 16, 17, 18, 19])

In [11]:
other_array_1d = np.arange(50, 60)
other_array_1d

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [12]:
np.where(array_1d < 4, array_1d, other_array_1d)

array([ 0,  1,  2,  3, 54, 55, 56, 57, 58, 59])

In [13]:
array_2d = np.arange(0, 20).reshape(4, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
np.where(array_2d % 2 == 0, array_2d, -1)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1]])

## `np.argwere`

In [15]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
np.argwhere(array_2d % 2 == 0)

array([[0, 0],
       [0, 2],
       [0, 4],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [2, 4],
       [3, 1],
       [3, 3]])

## `np.selectc`

In [17]:
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.select(condlist=[array_1d < 4, array_1d > 7], choicelist=[array_1d + 10, array_1d + 20], default=-1)

array([10, 11, 12, 13, -1, -1, -1, -1, 28, 29])

## `np.unravel_index`

In [19]:
shape = (4, 5)
array = np.arange(20).reshape(shape)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
np.unravel_index(indices = 12, shape = shape)

(np.int64(2), np.int64(2))

## `np.diag_indices`

In [21]:
indices = np.diag_indices(n = 3, ndim = 2)
indices

(array([0, 1, 2]), array([0, 1, 2]))

In [22]:
array = np.arange(0,9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
array[indices] = -1
array

array([[-1,  1,  2],
       [ 3, -1,  5],
       [ 6,  7, -1]])

## `np.tril_indices`

In [24]:
indices = np.tril_indices(n = 3, m = 3)
indices

(array([0, 1, 1, 2, 2, 2]), array([0, 0, 1, 0, 1, 2]))

In [25]:
array = np.arange(0,9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
array[indices] = -1
array

array([[-1,  1,  2],
       [-1, -1,  5],
       [-1, -1, -1]])

## `np.triu_indices`

In [27]:
indices = np.triu_indices(n = 3, m = 3)
indices

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 2, 1, 2, 2]))

In [28]:
array = np.arange(0,9).reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
array[indices] = -1
array

array([[-1, -1, -1],
       [ 3, -1, -1],
       [ 6,  7, -1]])

## `np.diag_indices_from, np.tril_indices_from, np.triu_indices_from`

In [30]:
np.diag_indices_from(array)

(array([0, 1, 2]), array([0, 1, 2]))

In [31]:
np.tril_indices_from(array)

(array([0, 1, 1, 2, 2, 2]), array([0, 0, 1, 0, 1, 2]))

In [32]:
np.triu_indices_from(array)

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 2, 1, 2, 2]))