In [1]:
import numpy as np

# Estatística

In [2]:
rng = np.random.default_rng(seed = 5)

In [4]:
vector_1 = rng.integers(low=-10, high=10, size=4)
vector_1

array([-1,  0,  2, -5])

In [5]:
matrix_1 = rng.integers(low=-10, high=10, size=12).reshape(4,3)
matrix_1

array([[  9,  -9,  -5],
       [ -3,   1,  -2],
       [ -8, -10, -10],
       [-10,  -8,   9]])

`np.percentile`

In [6]:
np.percentile(a = vector_1, q = 10)

np.float64(-3.8)

In [7]:
np.percentile(a = vector_1, q = 50) #mediana

np.float64(-0.5)

In [8]:
np.percentile(a = vector_1, q = 90) 

np.float64(1.4000000000000004)

In [9]:
np.percentile(a = matrix_1, q = 50)

np.float64(-6.5)

`np.quantile`

In [10]:
np.quantile(a = vector_1, q = 0.1)

np.float64(-3.8)

In [11]:
np.quantile(a = vector_1, q = 0.5)

np.float64(-0.5)

In [12]:
np.quantile(a = matrix_1, q = 0.5)

np.float64(-6.5)

In [13]:
np.quantile(a = matrix_1, q = 0.5, axis=1)

array([ -5.,  -2., -10.,  -8.])

`np.percentile`

`np.percentile`

`np.percentile`

`np.percentile`

`np.percentile`