In [ ]:
import numpy as np
np.__version__

'1.25.2'

### Produtos matriciais e vetoriais

O array abaixo representa as notas de 5 alunos em 4 provas realizadas ao longo de um semestre.

In [ ]:
rng = np.random.default_rng(seed=5)

In [ ]:
scores = np.clip( # limita as notas para o intervalo [0, 10]
    a=np.round( # arredondamento das notas para 1 cada decimal
        a=rng.normal(loc=7, scale=2, size=20), # amostra de números com distribuição normal
        decimals=1
        ),
    a_min=0,
    a_max=10
).reshape(5, 4) # altera para o shape desejado

In [ ]:
scores

array([[ 5.4,  4.4,  6.5,  7.8],
       [ 9.3,  7.2,  5.9,  5.4],
       [ 8.5, 10. ,  7.5,  4.5],
       [ 5.1, 10. ,  7.4,  3.5],
       [ 6.8,  4.7,  5.7,  6. ]])

👆 5 alunos (5 linhas), 4 notas (4 colunas).

Para calcular a média, o professor decidiu aplicar pesos diferentes a cada prova, conforme o array abaixo.

In [ ]:
weights = np.array([[0.2],
                    [0.3],
                    [0.4],
                    [0.1]])

In [ ]:
weights

array([[0.2],
       [0.3],
       [0.4],
       [0.1]])

#### `np.dot`

Utilize `np.dot` para calcular o produto entre as matrizes `scores` e `weights`.

In [ ]:
...

array([[5.78],
       [6.92],
       [8.15],
       [7.33],
       [5.65]])

Observe que o resultado representa a **média ponderada** dos alunos.

#### `np.vdot`

Utilize indexação para separar as notas do aluno de índice 2 em uma nova variável.

In [ ]:
scores_2 = ...

In [ ]:
scores_2

array([ 8.5, 10. ,  7.5,  4.5])

Agora utilize `np.vdot` para determinar a média ponderada do aluno 2. Lembre-se que, como esta função só aceita vetores, você precisa linearizar `weights`, que está no formato de matriz. Pode utilizar tanto o método `ravel` quanto `flatten`, e pode aplicar este método no array `weights` diretamente na chamada da função `np.vdot`.

In [ ]:
...

8.15

Observe que é o mesmo resultado obtido para o aluno 2 no exercício utilizando `np.dot`.

####  `np.inner`

Refaça o mesmo cálculo mas utilizando a função `np.inner`.

In [ ]:
...

8.15

Lembre-se que, para dois vetores, o produto interno (`inner`) é igual ao produto vetorial (`dot` ou `vdot`).

#### `np.matmul`

Mais uma vez refaça o cálculo usando `np.matmul`.

In [ ]:
...

8.15

A multiplicação "matricial" entre dois vetores também corresponde ao produto vetorial entre eles.

#### `np.outer`

Esta função é útil quando queremos montar uma matriz a partir da multiplicação de dois vetores, onde os valores sejam o resultado da mutiplicação de todos os valores dos vetores.

Dados os dois vetores abaixo:

In [ ]:
array_0 = np.array([2, 3, 7])
array_1 = np.array([0.7, 0.2, 0.3, 0.4])

Determine a matriz que é obtida pela operação discriminada acima.

In [ ]:
...

array([[1.4, 0.4, 0.6, 0.8],
       [2.1, 0.6, 0.9, 1.2],
       [4.9, 1.4, 2.1, 2.8]])

Observe que o formato da matriz reflete os comprimentos dos vetores: 3x4.

#### `np.linalg.det`

O determinante de uma matriz quadrada é utilizado para calcular sua matriz inversa.

Calcule o determinante da matriz abaixo.

In [ ]:
array_2 = rng.normal(loc=5, scale=2, size=16).reshape(4, 4)

In [ ]:
array_2

array([[3.57337326, 6.10675694, 4.87382806, 3.82113748],
       [5.81927565, 6.65971061, 1.71395326, 4.48653975],
       [3.03850529, 4.65368955, 2.42116251, 5.04138079],
       [4.92422852, 4.3913245 , 2.90414699, 4.20761934]])

In [ ]:
...

101.71871198583534

#### `np.linalg.inv`

Mas você também pode obter a inversa diretamente com a função `np.linalg.inv`. Faça isso para `array_2`.

In [ ]:
array_2_inv = ...

In [ ]:
array_2_inv

array([[-0.12133586,  0.03653967, -0.30410658,  0.43559582],
       [ 0.18856179,  0.30405942,  0.00121017, -0.49690715],
       [ 0.21974751, -0.27338361, -0.12332989,  0.2397113 ],
       [-0.20646582, -0.17140502,  0.43976035,  0.08103165]])

Utilize `np.matmul` para confirmar que a multiplicação matricial entre uma matriz e sua inversa resulta na matriz identidade, onde os valores da diagonal são iguais a 1 e os demais são 0.

In [ ]:
array_mul = ...

In [ ]:
array_mul

array([[ 1.00000000e+00, -2.28370863e-16, -4.34034021e-17,
        -1.88323981e-16],
       [-1.56417331e-16,  1.00000000e+00,  2.45108307e-16,
         3.63683316e-17],
       [-1.72780463e-16, -2.91534209e-16,  1.00000000e+00,
        -1.67128393e-16],
       [ 3.04949725e-17, -3.01842060e-16, -1.31248302e-16,
         1.00000000e+00]])

Estes valores estão difíceis de interpretar por causa dos arredondamentos que o NumPy fez.

Vamos instanciar uma matriz identidade no mesmo formato de `array_mul`. Isto é feito com a função `np.identity`.

In [ ]:
array_identity = ...

In [ ]:
array_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Por fim, utilize `np.allclose` para verificar que os valores de `array_mul` são virtualmente iguais a `array_identity`.

In [ ]:
...

True