# Números Aleatórios

In [5]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
matplotlib.__version__

'3.10.0'

## Gerador de dados aleatórios

### `np.random.default_rgn`

In [7]:
rng = np.random.default_rng(seed = 1)
rng

Generator(PCG64) at 0x7717C1685B60

In [9]:
rng = np.random.default_rng(seed = 2)
rng.random()

0.2616121342493164

In [10]:
rng.random(size = 10)

array([0.29849114, 0.81422574, 0.09191594, 0.60010053, 0.72856053,
       0.18790107, 0.05514663, 0.27496937, 0.65743301, 0.56226566])

In [11]:
rng.random(size = (5, 2))

array([[0.15006226, 0.43263079],
       [0.6692973 , 0.42278467],
       [0.6331844 , 0.96743595],
       [0.68306482, 0.39162483],
       [0.18725257, 0.34596067]])

## Dados aleatórios simples

### `rng.integers`

In [15]:
rng.integers(4, size = 5)

array([2, 3, 3, 3, 3])

In [16]:
rng.integers(low = 10, high = 50, size = 5)

array([22, 46, 46, 18, 28])

In [20]:
rng.integers(low = 10, high = [15,54,100])

array([14, 18, 50])

### `rng.choice`

In [22]:
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
rng.choice(a = array)

np.int64(8)

In [24]:
rng.choice(a = array, size = 5)

array([5, 6, 4, 8, 5])

In [25]:
rng.choice(a = array, size = 10)

array([6, 4, 4, 5, 5, 7, 5, 4, 8, 2])

In [26]:
rng.choice(a = array, size = 10, replace=False)

array([1, 7, 3, 9, 8, 4, 2, 5, 6, 0])

In [27]:
array = np.array([1, 2, 3])
p = np.array([0.5, 0.4, 0.1]) # soma deve ser igual a 1 (100%)

In [28]:
rng.choice(a = array, size = 10, p = p)

array([1, 2, 1, 2, 2, 1, 3, 2, 2, 1])

In [30]:
array_2d = np.arange(0, 20).reshape(4, 5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
rng.choice(a = array_2d, size = 2, axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
rng.choice(a = array_2d, size = 2, axis = 1)

array([[ 0,  4],
       [ 5,  9],
       [10, 14],
       [15, 19]])