In [2]:
import numpy as np

# Arrays preenchidas

## `np.zeros`

In [3]:
np.zeros(shape = 3)

array([0., 0., 0.])

In [5]:
np.zeros(shape = (2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros(shape = (2,3)).dtype

dtype('float64')

## `np.ones`

In [7]:
np.ones(shape = (2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## `np.full`

In [8]:
np.full(shape = (2, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [9]:
array = np.array([[1,2,3],
                 [4,5,6]])

In [10]:
array.shape

(2, 3)

In [12]:
np.zeros_like(a=array)

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
np.ones_like(a=array)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.full_like(a=array, fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

## `np.empty`

In [17]:
np.empty(shape = (2, 3))

array([[3.39100397e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

## `np.eye`

In [19]:
np.eye(N=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(N=5, M=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

## `np.identity`

In [21]:
np.identity(n = 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## `np.arange`

In [22]:
np.arange(stop = 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(start = 3, stop = 10)

array([3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(start = 3, stop = 10, step = 3)

array([3, 6, 9])

In [27]:
np.arange(start = 10, stop = 3, step = -2)

array([10,  8,  6,  4])

In [28]:
np.arange(start = 3, stop = 5, step = 0.25)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

## `np.linspace`

In [30]:
np.linspace(start = 1, stop = 10, num = 4)

array([ 1.,  4.,  7., 10.])

In [32]:
np.linspace(start = 1, stop = 10, num = 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## `np.logspace`

In [33]:
np.logspace(start = 1, stop = 4, num = 4)

array([   10.,   100.,  1000., 10000.])

## `np.geomspace`

In [34]:
np.geomspace(start = 10, stop = 10000, num = 4)

array([   10.,   100.,  1000., 10000.])